export const PERMISSIONS = {
  ANNULER_COMMANDE: "ANNULER_COMMANDE",
  VOIR_BILANS_GLOBAUX: "VOIR_BILANS_GLOBAUX",
  CLOTURER_CAISSE: "CLOTURER_CAISSE",
  LIVRER_COMMANDE: "LIVRER_COMMANDE",
  TERMINER_COMMANDE: "TERMINER_COMMANDE",
  MODIFIER_PARAMETRES: "MODIFIER_PARAMETRES",
  GERER_UTILISATEURS: "GERER_UTILISATEURS"
};
