export const PERMISSIONS = {
  ANNULER_COMMANDE: "ANNULER_COMMANDE",
  VOIR_CLIENTS: "VOIR_CLIENTS",
  CREER_CLIENT: "CREER_CLIENT",
  MODIFIER_CLIENT: "MODIFIER_CLIENT",
  DESACTIVER_CLIENT: "DESACTIVER_CLIENT",
  VOIR_COMMANDES: "VOIR_COMMANDES",
  CREER_COMMANDE: "CREER_COMMANDE",
  VOIR_RETOUCHES: "VOIR_RETOUCHES",
  CREER_RETOUCHE: "CREER_RETOUCHE",
  VOIR_BILANS_GLOBAUX: "VOIR_BILANS_GLOBAUX",
  GERER_STOCK: "GERER_STOCK",
  GERER_VENTES: "GERER_VENTES",
  GERER_ACHATS_STOCK: "GERER_ACHATS_STOCK",
  GERER_AJUSTEMENTS_STOCK: "GERER_AJUSTEMENTS_STOCK",
  VOIR_AUDIT_STOCK: "VOIR_AUDIT_STOCK",
  OUVRIR_CAISSE: "OUVRIR_CAISSE",
  ENREGISTRER_ENTREE_CAISSE: "ENREGISTRER_ENTREE_CAISSE",
  ENREGISTRER_SORTIE_CAISSE: "ENREGISTRER_SORTIE_CAISSE",
  ANNULER_OPERATION_CAISSE: "ANNULER_OPERATION_CAISSE",
  CLOTURER_CAISSE: "CLOTURER_CAISSE",
  LIVRER_COMMANDE: "LIVRER_COMMANDE",
  TERMINER_COMMANDE: "TERMINER_COMMANDE",
  MODIFIER_PARAMETRES: "MODIFIER_PARAMETRES",
  GERER_UTILISATEURS: "GERER_UTILISATEURS",
  GERER_ATELIERS: "GERER_ATELIERS"
};

const SYSTEM_ONLY_PERMISSIONS = new Set([PERMISSIONS.GERER_ATELIERS]);

export function isSystemOnlyPermission(permission) {
  return SYSTEM_ONLY_PERMISSIONS.has(String(permission || "").trim().toUpperCase());
}

export function listTenantPermissions() {
  return Object.values(PERMISSIONS).filter((permission) => !SYSTEM_ONLY_PERMISSIONS.has(permission));
}

export function listSystemPermissions() {
  return [PERMISSIONS.GERER_ATELIERS];
}
