// Value objects & enums for Retouche
export const StatutRetouche = Object.freeze({
  DEPOSEE: "DEPOSEE",
  EN_COURS: "EN_COURS",
  TERMINEE: "TERMINEE",
  LIVREE: "LIVREE",
  ANNULEE: "ANNULEE"
});

export const TypeRetouche = Object.freeze({
  OURLET_PANTALON: "OURLET_PANTALON",
  DIMINUER_LONGUEUR_PANTALON: "DIMINUER_LONGUEUR_PANTALON",
  RESSERRER_TAILLE_PANTALON: "RESSERRER_TAILLE_PANTALON",
  AGRANDIR_TAILLE_PANTALON: "AGRANDIR_TAILLE_PANTALON",
  AJUSTER_BAS_PANTALON: "AJUSTER_BAS_PANTALON",
  RESSERRER_TAILLE_CHEMISE: "RESSERRER_TAILLE_CHEMISE",
  AGRANDIR_TAILLE_CHEMISE: "AGRANDIR_TAILLE_CHEMISE",
  REDUIRE_MANCHES_CHEMISE: "REDUIRE_MANCHES_CHEMISE",
  RESSERRER_ROBE: "RESSERRER_ROBE",
  AGRANDIR_ROBE: "AGRANDIR_ROBE",
  AJUSTER_LONGUEUR_ROBE: "AJUSTER_LONGUEUR_ROBE",
  REPARATION_DECHIRURE: "REPARATION_DECHIRURE",
  REMPLACER_FERMETURE: "REMPLACER_FERMETURE",
  SURFILAGE: "SURFILAGE",
  POSER_BOUTON: "POSER_BOUTON",
  BRODERIE: "BRODERIE",
  ZIGZAG: "ZIGZAG",
  AUTRES: "AUTRES",
  // Compat legacy
  OURLET: "OURLET",
  RESSERRAGE: "RESSERRAGE",
  AGRANDISSEMENT: "AGRANDISSEMENT",
  REPARATION: "REPARATION",
  FERMETURE: "FERMETURE",
  AUTRE: "AUTRE"
});

export function assertNonEmpty(value, label) {
  if (!value || String(value).trim().length === 0) {
    throw new Error(`${label} ne doit pas etre vide`);
  }
}
