ALTER TABLE ventes ADD COLUMN IF NOT EXISTS total_prix_achat NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE ventes ADD COLUMN IF NOT EXISTS benefice_total NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE vente_lignes ADD COLUMN IF NOT EXISTS prix_achat_unitaire NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE vente_lignes ADD COLUMN IF NOT EXISTS benefice_unitaire NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE vente_lignes ADD COLUMN IF NOT EXISTS benefice_total NUMERIC(12,2) NOT NULL DEFAULT 0;
